# Use the official Node.js image as a base
FROM node:20-buster


# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose the port that the application will run on
EXPOSE 5000

# Define environment variables
ENV DATABASE_URL=mongodb+srv://bikeRental:IdhBuqSVoSnInUXi@cluster0.hxdwxas.mongodb.net/bikeRentDB?retryWrites=true&w=majority&appName=Cluster0
ENV PORT=5000
ENV NODE_ENV=development
ENV BCRYPT_SALT_ROUNDS=10
ENV JWT_TOKEN_SECRET=a19e370c6bb9390dacc0ce3d809fe054b0a009abcc3077a3f5c14be65d98faa4d2fa1c19de0e9790bf2f8fcd4cb13a150ed6b9daded671540f21e0d66d2263fa

# Start the application
CMD ["npm", "start"]
